package net.tamashi.fomekcore.api.guisystems;

import net.minecraft.client.Minecraft;
import com.mojang.blaze3d.platform.InputConstants;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.lwjgl.glfw.GLFW;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * InputManager — keyboard/mouse input router for the virtual GUI system.
 *
 * An InputManager is registered with an id, a frequency (tick/frame/second),
 * and a list of event registrations (key + event type + action id).
 *
 * Each poll, the manager checks all registered events and fires the matching
 * action via VirtualGui.callAction(), recording the manager's id as the
 * "action manager id" so the user's Action block can check which InputManager
 * triggered it (useful when multiple managers bind the same action).
 *
 * Event types:
 *   key_down    — fires once on the frame the key transitions from up→down
 *   key_up      — fires once on the frame the key transitions from down→up
 *   key_held    — fires every poll while the key is held down
 *   scroll_up   — fires on mouse wheel scroll up (delta > 0)
 *   scroll_down — fires on mouse wheel scroll down (delta < 0)
 *
 * Frequencies:
 *   tick   — polled every client tick (20x/sec)
 *   frame  — polled every render frame (fps-dependent, default)
 *   second — polled once per second
 *
 * Usage (generated by the FomekMenus plugin):
 *   InputManager.register("mgr1", "tick");
 *   InputManager.registerEvent("mgr1", "key.keyboard.a", "key_held", "action_move_left");
 *   InputManager.registerEvent("mgr1", "key.keyboard.d", "key_held", "action_move_right");
 *   InputManager.updateAll();  // called automatically by VirtualGui.onScreenRender
 */
@OnlyIn(Dist.CLIENT)
public class InputManager {

    // ── Registration data ──────────────────────────────────────────────────────

    private static class EventEntry {
        final String keyName;
        final String eventType;
        final String actionId;

        EventEntry(String keyName, String eventType, String actionId) {
            this.keyName = keyName;
            this.eventType = eventType;
            this.actionId = actionId;
        }
    }

    private static class Manager {
        final String id;
        final String frequency;
        final List<EventEntry> events = new CopyOnWriteArrayList<>();
        long lastSecondCheck = 0;

        Manager(String id, String frequency) {
            this.id = id;
            this.frequency = frequency;
        }
    }

    private static final Map<String, Manager> managers = new ConcurrentHashMap<>();
    private static final List<Manager> tickManagers = new CopyOnWriteArrayList<>();
    private static final List<Manager> frameManagers = new CopyOnWriteArrayList<>();
    private static final List<Manager> secondManagers = new CopyOnWriteArrayList<>();

    // Key state tracking for edge detection (key_down / key_up)
    private static final Set<String> keysDown = ConcurrentHashMap.newKeySet();

    // Scroll delta accumulator (fed by ScrollEventHandler, consumed by poll)
    private static volatile double scrollDeltaAccum = 0;

    /** Tracks which (key:eventType) pairs fired this tick (for tick-frequency managers). */
    private static final java.util.Set<String> firedThisTick = java.util.concurrent.ConcurrentHashMap.newKeySet();
    /** Tracks which (key:eventType) pairs fired this frame (for frame-frequency managers). */
    private static final java.util.Set<String> firedThisFrame = java.util.concurrent.ConcurrentHashMap.newKeySet();

    // ── Called input tracking (the input that triggered the current action) ────
    //
    // When pollManager fires an action, it records which key + event type
    // triggered it. The action body can then query this to check what input
    // was used (e.g. "is called input of type character?" → A=true, ESC=false).

    private static volatile String calledInputKey = "";
    private static volatile String calledInputEventType = "";

    // ── Registration API ───────────────────────────────────────────────────────

    /**
     * Register (or re-register) an InputManager. Idempotent — safe to call
     * every frame from the render procedure. If the frequency changed, the
     * old registration is replaced.
     */
    public static void register(String id, String frequency) {
        Manager mgr = managers.get(id);
        if (mgr != null && mgr.frequency.equals(frequency)) return;

        if (mgr != null) {
            tickManagers.remove(mgr);
            frameManagers.remove(mgr);
            secondManagers.remove(mgr);
        }

        mgr = new Manager(id, frequency);
        managers.put(id, mgr);
        switch (frequency) {
            case "tick": tickManagers.add(mgr); break;
            case "second": secondManagers.add(mgr); break;
            default: frameManagers.add(mgr); break;
        }
    }

    /**
     * Register an event for an InputManager. Idempotent — skips duplicates.
     */
    public static void registerEvent(String managerId, String keyName, String eventType, String actionId) {
        Manager mgr = managers.get(managerId);
        if (mgr == null) return;

        for (EventEntry e : mgr.events) {
            if (e.keyName.equals(keyName) && e.eventType.equals(eventType) && e.actionId.equals(actionId)) {
                return;
            }
        }
        mgr.events.add(new EventEntry(keyName, eventType, actionId));
    }

    // ── Scroll input ───────────────────────────────────────────────────────────

    /**
     * Feed scroll delta into the InputManager system. Called by
     * ScrollEventHandler when a scroll event occurs and no scroll view
     * consumed it, or by VirtualGui directly.
     */
    public static void feedScrollDelta(double delta) {
        scrollDeltaAccum += delta;
    }

    // ── Polling ─────────────────────────────────────────────────────────────────

    /** Update all frame-frequency managers. Called every render frame. */
    public static void updateFrame() {
        firedThisFrame.clear();
        for (Manager mgr : frameManagers) {
            pollManager(mgr);
        }
    }

    /** Update all tick-frequency managers. */
    public static void updateTick() {
        firedThisTick.clear();
        for (Manager mgr : tickManagers) {
            pollManager(mgr);
        }
    }

    /** Update all second-frequency managers (once per second per manager). */
    public static void updateSecond() {
        long now = System.currentTimeMillis();
        for (Manager mgr : secondManagers) {
            if (now - mgr.lastSecondCheck >= 1000) {
                mgr.lastSecondCheck = now;
                pollManager(mgr);
            }
        }
    }

    /**
     * Convenience: update frame + second frequencies. Called by
     * VirtualGui.onScreenRender each frame. Tick managers are polled
     * separately via updateTick() (hooked by VirtualGui on ClientTickEvent).
     */
    public static void updateAll() {
        updateFrame();
        updateSecond();
    }

    /**
     * Check if a specific input event was routed (fired) this frame.
     * Use inside an Action block that was triggered by an InputManager event.
     *
     * @param keyName   The key identifier (e.g. "key.keyboard.w", "mouse.left")
     * @param eventType The event type ("key_held", "key_down", "key_up",
     *                  "scroll_up", "scroll_down")
     * @return true if the event fired this frame
     */
    public static boolean isInputRouted(String keyName, String eventType) {
        String key = keyName + ":" + eventType;
        return firedThisFrame.contains(key) || firedThisTick.contains(key);
    }

    // ── Called input API (the input that triggered the current action) ──────────

    /**
     * Get the key name of the input that triggered the current action.
     * e.g. "key.keyboard.w", "mouse.left"
     *
     * Use inside an Action block that was triggered by an InputManager event.
     */
    public static String getCalledInputKey() {
        return calledInputKey;
    }

    /**
     * Get the event type of the input that triggered the current action.
     * e.g. "key_held", "key_down", "key_up", "scroll_up", "scroll_down"
     */
    public static String getCalledInputEventType() {
        return calledInputEventType;
    }

    /**
     * Check if the called input key matches a type category.
     *
     * @param type One of: "character", "letter", "number", "special", "mouse"
     *   character — printable keys that produce a character (a-z, 0-9, space)
     *   letter    — just a-z
     *   number    — just 0-9
     *   special   — non-printable keys (escape, shift, ctrl, tab, arrows, F-keys, etc.)
     *   mouse     — mouse buttons (left, right, middle)
     */
    public static boolean isCalledInputOfType(String type) {
        if (calledInputKey == null || calledInputKey.isEmpty()) return false;
        switch (type) {
            case "character": return isCharacterKey(calledInputKey);
            case "letter":    return isLetterKey(calledInputKey);
            case "number":    return isNumberKey(calledInputKey);
            case "special":   return isSpecialKey(calledInputKey);
            case "mouse":     return calledInputKey.startsWith("mouse.");
            default:          return false;
        }
    }

    /**
     * Check if the called input event type matches.
     * @param eventType One of: "key_held", "key_down", "key_up", "scroll_up", "scroll_down"
     */
    public static boolean isCalledInputOfEventType(String eventType) {
        return eventType != null && eventType.equals(calledInputEventType);
    }

    // ── Key classification helpers ──────────────────────────────────────────────

    private static boolean isLetterKey(String keyName) {
        // key.keyboard.a through key.keyboard.z
        if (!keyName.startsWith("key.keyboard.")) return false;
        String suffix = keyName.substring("key.keyboard.".length());
        return suffix.length() == 1 && suffix.charAt(0) >= 'a' && suffix.charAt(0) <= 'z';
    }

    private static boolean isNumberKey(String keyName) {
        if (!keyName.startsWith("key.keyboard.")) return false;
        String suffix = keyName.substring("key.keyboard.".length());
        return suffix.length() == 1 && suffix.charAt(0) >= '0' && suffix.charAt(0) <= '9';
    }

    private static boolean isCharacterKey(String keyName) {
        // Printable characters: letters, numbers, space
        return isLetterKey(keyName) || isNumberKey(keyName) || "key.keyboard.space".equals(keyName);
    }

    private static boolean isSpecialKey(String keyName) {
        // Non-printable keys: everything that's not a character and not a mouse button
        if (keyName.startsWith("mouse.")) return false;
        return !isCharacterKey(keyName);
    }

    // ── Register all keys ──────────────────────────────────────────────────────

    /**
     * Register ALL keyboard keys + mouse buttons + scroll wheel with ALL event
     * types (key_held, key_down, key_up, scroll_up, scroll_down) to one action.
     * Useful for text input (notepad) where any key should trigger the same
     * action. Inside the action, use isCalledInputOfType / isCalledInputOfEventType
     * to filter which input you care about.
     *
     * @param managerId The InputManager id to register events for
     * @param actionId  The action id to route all inputs to
     */
    public static void registerAllKeys(String managerId, String actionId) {
        // Register ALL keys with ALL event types (key_held, key_down, key_up)
        // plus scroll events (scroll_up, scroll_down) for the scroll wheel.
        // Any input on any key will fire the action — use isCalledInputOfEventType
        // and isCalledInputOfType inside the action to filter.

        String[] keyEventTypes = {"key_held", "key_down", "key_up"};

        // All letter keys a-z
        for (char c = 'a'; c <= 'z'; c++) {
            for (String et : keyEventTypes)
                registerEvent(managerId, "key.keyboard." + c, et, actionId);
        }
        // All number keys 0-9
        for (char c = '0'; c <= '9'; c++) {
            for (String et : keyEventTypes)
                registerEvent(managerId, "key.keyboard." + c, et, actionId);
        }
        // All special keys
        String[] specialKeys = {
            "key.keyboard.space", "key.keyboard.enter", "key.keyboard.tab",
            "key.keyboard.escape", "key.keyboard.backspace", "key.keyboard.delete",
            "key.keyboard.insert", "key.keyboard.home", "key.keyboard.end",
            "key.keyboard.page.up", "key.keyboard.page.down",
            "key.keyboard.left.shift", "key.keyboard.right.shift",
            "key.keyboard.left.ctrl", "key.keyboard.right.ctrl",
            "key.keyboard.left.alt", "key.keyboard.right.alt",
            "key.keyboard.left.win", "key.keyboard.right.win",
            "key.keyboard.up", "key.keyboard.down",
            "key.keyboard.left", "key.keyboard.right",
            "key.keyboard.caps.lock", "key.keyboard.num.lock", "key.keyboard.scroll.lock",
            "key.keyboard.pause", "key.keyboard.print.screen", "key.keyboard.menu",
            "key.keyboard.grave.accent", "key.keyboard.minus", "key.keyboard.equals",
            "key.keyboard.left.bracket", "key.keyboard.right.bracket",
            "key.keyboard.backslash", "key.keyboard.semicolon", "key.keyboard.apostrophe",
            "key.keyboard.comma", "key.keyboard.period", "key.keyboard.slash",
        };
        for (String key : specialKeys) {
            for (String et : keyEventTypes)
                registerEvent(managerId, key, et, actionId);
        }
        // Function keys F1-F12
        for (int i = 1; i <= 12; i++) {
            for (String et : keyEventTypes)
                registerEvent(managerId, "key.keyboard.f" + i, et, actionId);
        }
        // Mouse buttons
        for (String et : keyEventTypes) {
            registerEvent(managerId, "mouse.left", et, actionId);
            registerEvent(managerId, "mouse.right", et, actionId);
            registerEvent(managerId, "mouse.middle", et, actionId);
        }
        // Scroll wheel — scroll up + scroll down
        registerEvent(managerId, "key.mouse.wheel", "scroll_up", actionId);
        registerEvent(managerId, "key.mouse.wheel", "scroll_down", actionId);
    }

    // ── Core polling logic ─────────────────────────────────────────────────────

    private static void pollManager(Manager mgr) {
        // Note: firedThisFrame is cleared in updateFrame, firedThisTick in updateTick,
        // not here, so events from all managers accumulate within a single cycle.
        boolean scrollUp = false;
        boolean scrollDown = false;
        if (scrollDeltaAccum != 0) {
            if (scrollDeltaAccum > 0) scrollUp = true;
            else scrollDown = true;
        }

        for (EventEntry e : mgr.events) {
            boolean fire = false;

            if ("scroll_up".equals(e.eventType)) {
                fire = scrollUp;
            } else if ("scroll_down".equals(e.eventType)) {
                fire = scrollDown;
            } else {
                boolean isDown = isKeyDown(e.keyName);

                switch (e.eventType) {
                    case "key_held":
                        fire = isDown;
                        break;
                    case "key_down":
                        fire = isDown && !keysDown.contains(e.keyName);
                        break;
                    case "key_up":
                        fire = !isDown && keysDown.contains(e.keyName);
                        break;
                }

                if (isDown) keysDown.add(e.keyName);
                else keysDown.remove(e.keyName);
            }

            if (fire) {
                firedThisFrame.add(e.keyName + ":" + e.eventType);
                firedThisTick.add(e.keyName + ":" + e.eventType);
                calledInputKey = e.keyName;
                calledInputEventType = e.eventType;
                VirtualGui.setActionManagerId(mgr.id);
                VirtualGui.setActionReason("input_routed");
                VirtualGui.callAction(e.actionId);
            }
        }

        // Consume scroll delta after all managers have seen it
        scrollDeltaAccum = 0;
    }

    // ── Key state detection ────────────────────────────────────────────────────

    /**
     * Check if a key is currently held down.
     *
     * keyName formats:
     *   "key.keyboard.a" .. "key.keyboard.z"  — letter keys
     *   "key.keyboard.space", "key.keyboard.escape", etc. — named keys
     *   "key.keyboard.up", "key.keyboard.down", etc. — arrow keys
     *   "mouse.left", "mouse.right", "mouse.middle" — mouse buttons
     *
     * Uses GLFW directly via InputConstants (Minecraft's key abstraction).
     */
    private static boolean isKeyDown(String keyName) {
        if (keyName == null || keyName.isEmpty()) return false;

        long handle = Minecraft.getInstance().getWindow().getWindow();

        // Mouse buttons
        if (keyName.startsWith("mouse.")) {
            int button = switch (keyName) {
                case "mouse.left" -> 0;
                case "mouse.right" -> 1;
                case "mouse.middle" -> 2;
                default -> -1;
            };
            if (button < 0) return false;
            return GLFW.glfwGetMouseButton(handle, button) == GLFW.GLFW_PRESS;
        }

        // Keyboard keys — use Minecraft's InputConstants to resolve the key
        try {
            InputConstants.Key key = InputConstants.getKey(keyName);
            int keyCode = key.getValue();
            // For keys < 32, InputConstants uses mouse codes — check via GLFW mouse
            if (keyCode >= 0) {
                return GLFW.glfwGetKey(handle, keyCode) == GLFW.GLFW_PRESS;
            }
        } catch (Exception ignored) {
        }

        // Fallback: try GLFW field name directly
        String glfwName = keyName.replace("key.keyboard.", "GLFW_KEY_").toUpperCase();
        try {
            java.lang.reflect.Field f = GLFW.class.getField(glfwName);
            int keyCode = f.getInt(null);
            return GLFW.glfwGetKey(handle, keyCode) == GLFW.GLFW_PRESS;
        } catch (Exception ignored) {
        }

        // Final fallback: check Minecraft key mappings
        Minecraft mc = Minecraft.getInstance();
        if (mc.options == null) return false;
        if ("mouse.left".equals(keyName)) return mc.options.keyAttack.isDown();
        if ("mouse.right".equals(keyName)) return mc.options.keyUse.isDown();
        return false;
    }

    // ── Current manager tracking (for child Register Event blocks) ─────────────

    private static String currentManagerId = null;

    /** Set the current manager id — called by the Input Manager block before
     *  its DO statement, so Register Event blocks inside know which manager
     *  to register events for. */
    public static void setCurrentManagerId(String id) {
        currentManagerId = id;
    }

    public static String getCurrentManagerId() {
        return currentManagerId;
    }

    // ── Input cancellation (prevents vanilla from processing a key) ──────────────
    //
    // When a key is cancelled, the KeyboardHandlerMixin and mouse handler
    // will suppress vanilla processing of that key on the CLIENT side.
    // The key is still tracked by the InputManager and actions still fire.
    // The packet is still sent to the server — only client-side vanilla
    // behavior (pause menu, movement, hotbar, etc.) is suppressed.
    //
    // Usage: call cancelInput("key.keyboard.escape") to intercept ESC,
    //        call resumeInput("key.keyboard.escape") to restore vanilla behavior.

    private static final Set<String> cancelledInputKeys = ConcurrentHashMap.newKeySet();

    /** Cancel (suppress) vanilla client-side processing of a key. */
    public static void cancelInput(String keyName) {
        cancelledInputKeys.add(keyName);
    }

    /** Restore vanilla client-side processing of a key. */
    public static void resumeInput(String keyName) {
        cancelledInputKeys.remove(keyName);
    }

    /** Cancel (suppress) the called input — the key that triggered the current
     *  action via an InputManager event. No parameter needed. */
    public static void cancelCalledInput() {
        if (calledInputKey != null && !calledInputKey.isEmpty()) {
            cancelledInputKeys.add(calledInputKey);
        }
    }

    /** Resume (restore) the called input — the key that triggered the current
     *  action via an InputManager event. */
    public static void resumeCalledInput() {
        if (calledInputKey != null && !calledInputKey.isEmpty()) {
            cancelledInputKeys.remove(calledInputKey);
        }
    }

    /** Check if a key is currently cancelled (vanilla processing suppressed). */
    public static boolean isInputCancelled(String keyName) {
        return cancelledInputKeys.contains(keyName);
    }

    // ── Cleanup ─────────────────────────────────────────────────────────────────

    public static void clearAll() {
        managers.clear();
        tickManagers.clear();
        frameManagers.clear();
        secondManagers.clear();
        keysDown.clear();
        firedThisTick.clear();
        firedThisFrame.clear();
        scrollDeltaAccum = 0;
        currentManagerId = null;
        cancelledInputKeys.clear();
        calledInputKey = "";
        calledInputEventType = "";
    }
}
