package net.tamashi.fomekcore.api.guisystems;

/**
 * UpdateManager — fires update logic at a fixed frequency (tick/frame/second).
 *
 * Unlike InputManager (which uses the action system), UpdateManager uses a
 * simple shouldRun(frequency) check. No IDs needed — just call it inside
 * your render procedure and it returns true when it's time to run.
 *
 * <h3>Usage (generated by the FomekMenus plugin)</h3>
 * <pre>
 *   // Update block — no ID, just frequency:
 *   if (UpdateManager.shouldRun("tick")) {
 *       // move snake, check collisions, etc.
 *   }
 * </pre>
 *
 * <h3>Frequencies</h3>
 * <ul>
 *   <li><b>tick</b>  — runs on the first render frame after each client tick (20×/sec).</li>
 *   <li><b>frame</b> — runs every render frame (fps-dependent, typically 60+).</li>
 *   <li><b>second</b>— runs on the first render frame of each second (1×/sec).</li>
 * </ul>
 *
 * Multiple Update blocks of the same frequency all run together on the same
 * frame — shouldRun returns true for all of them, not just the first caller.
 */
public class UpdateManager {

    // ── Tick tracking ───────────────────────────────────────────────────────────
    // onClientTick sets tickPending = true. At the start of each render frame,
    // beginFrame() copies tickPending into tickFrame and clears it. All
    // shouldRun("tick") calls during that frame see tickFrame = true.

    private static volatile boolean tickPending = false;
    private static boolean tickFrame = false;

    // ── Second tracking ─────────────────────────────────────────────────────────
    // Same pattern: beginFrame() checks if >= 1000ms since last second run.

    private static long lastSecondRun = 0;
    private static boolean secondFrame = false;

    // ── Called by the engine ────────────────────────────────────────────────────

    /** Called from MenuEventHandler.onClientTick — marks that a tick occurred. */
    public static void onTick() {
        tickPending = true;
    }

    /**
     * Called at the START of each render frame (before user procedures run).
     * Computes which frequencies are active this frame.
     */
    public static void beginFrame() {
        // Tick: was a tick fired since the last frame?
        tickFrame = tickPending;
        tickPending = false;

        // Second: has >= 1 second passed since the last second run?
        long now = System.currentTimeMillis();
        secondFrame = (now - lastSecondRun >= 1000);
        if (secondFrame) {
            lastSecondRun = now;
        }
    }

    // ── Public API ──────────────────────────────────────────────────────────────

    /**
     * Returns true if this frequency should run on the current render frame.
     * Safe to call multiple times per frame — all callers get the same answer.
     *
     * @param frequency "tick", "frame", or "second"
     * @return true if the update should run this frame
     */
    public static boolean shouldRun(String frequency) {
        if (frequency == null) return false;
        switch (frequency) {
            case "tick":   return tickFrame;
            case "frame":  return true;
            case "second": return secondFrame;
            default:       return true; // unknown = run every frame
        }
    }

    // ── Cleanup ────────────────────────────────────────────────────────────────

    /** Reset all state (called when the screen closes). */
    public static void clearAll() {
        tickPending = false;
        tickFrame = false;
        secondFrame = false;
        lastSecondRun = 0;
    }
}
