package net.tamashi.fomek.renderer;

import net.mcreator.ui.MCreator;
import net.mcreator.workspace.Workspace;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.io.IOException;

/**
 * RendererRuntime — ported from FomekRendererPlugin (phase 3).
 *
 * On workspace load:
 * 1. Injects render API Java classes into <modpackage>.api.render
 * 2. Injects a [[mixins]] entry for fomek.mixins.json into neoforge.mods.toml's
 *    "custom mixins" user code block (MCreator preserves user code blocks
 *    across regenerations, so this survives).
 *
 * The mixin JAVA classes (ItemRendererMixin, ItemEntityRenderMixin,
 * MinecraftAccessorMixin) are generated by the generator.yaml base_templates
 * system. The fomek.mixins.json config file is also a base_template.
 *
 * We use a SEPARATE fomek.mixins.json file (not <modid>.mixins.json) because
 * other plugins (forge_mixins, player_animator) overwrite <modid>.mixins.json
 * during code generation, wiping our mixins. fomek.mixins.json is ours alone.
 */
public class RendererRuntime {

    private static final Logger LOG = LogManager.getLogger("Fomek Renderer");

    private static final String RENDAPI_SUFFIX = ".api.render";

    private static final String[] CLASS_TEMPLATES = {
        "RenderAPI.java",
        "FomekCoreCompat.java",
        "BEWRL.java",
        "BEWRLVars.java",
        "BEWRLStorage.java",
        "Shader.java",
        "RenderEvent.java",
        "RenderData.java",
        "Animation.java",
        "JavaModelRenderer.java",
        "ItemEntityFlags.java"
    };

    private static final String TEMPLATE_VERSION = "1.18.2";

    private static final String MIXIN_CONFIG_LINE = "[[mixins]]";
    private static final String MIXIN_CONFIG_VALUE = "    config = \"fomek.mixins.json\"";
    private static final String CUSTOM_MIXINS_START = "# Start of user code block custom mixins";
    private static final String CUSTOM_MIXINS_END = "# End of user code block custom mixins";



    /**
     * Called by FomekPlugin on MCreatorLoadedEvent.
     * Ported 1:1 from the original FomekRendererPlugin listener body.
     */
    public void onMCreatorLoaded(MCreator mcreator) {
        if (mcreator.getWorkspace() != null) {
            Workspace workspace = mcreator.getWorkspace();
            injectClasses(workspace);
            injectMixinConfig(workspace);
        }
    }


    private void injectClasses(Workspace workspace) {
        try {
            String modPackage = getModPackage(workspace);
            if (modPackage == null || modPackage.isEmpty()) {
                LOG.warn("Could not determine mod package, skipping injection");
                return;
            }

            String modId = getModId(workspace);
            if (modId == null || modId.isEmpty()) {
                // Fallback: derive modid from last package segment
                modId = modPackage.substring(modPackage.lastIndexOf('.') + 1);
                LOG.warn("Could not determine mod ID, derived from package: {}", modId);
            }

            String renderApiPackage = modPackage + RENDAPI_SUFFIX;
            String packagePath = renderApiPackage.replace('.', '/');
            String sourceRoot = getWorkspaceSourceRoot(workspace);
            String targetDir = sourceRoot + "/" + packagePath;

            LOG.info("Injecting render API classes into: {} (package: {}, modid: {})", targetDir, renderApiPackage, modId);

            File stampFile = new File(targetDir, ".render_api_stamp");
            if (stampFile.exists()) {
                String existingVersion = new String(Files.readAllBytes(stampFile.toPath())).trim();
                if (TEMPLATE_VERSION.equals(existingVersion)) {
                    LOG.info("Render API classes already up-to-date (v{}), skipping", TEMPLATE_VERSION);
                    return;
                }
            }

            new File(targetDir).mkdirs();

            for (String templateName : CLASS_TEMPLATES) {
                injectTemplate(templateName, targetDir, renderApiPackage, modPackage, modId);
            }

            Files.write(stampFile.toPath(), TEMPLATE_VERSION.getBytes());

            LOG.info("Injected {} render API classes into {}", CLASS_TEMPLATES.length, renderApiPackage);

        } catch (Exception e) {
            LOG.error("Failed to inject render API classes", e);
        }
    }

    /**
     * Injects [[mixins]] config = "fomek.mixins.json" into the
     * "custom mixins" user code block of neoforge.mods.toml.
     *
     * MCreator preserves content between user code block markers across
     * regenerations, so this is safe and survives code generation.
     *
     * IMPORTANT: This method only ADDS our entry if it's missing — it never
     * removes or overwrites other [[mixins]] entries that the user (or other
     * plugins) may have placed in the custom mixins block.
     *
     * The fomek.mixins.json file itself is generated by a base_template
     * (see generator.yaml), so we don't write it here.
     */
    private void injectMixinConfig(Workspace workspace) {
        try {
            String resourceRoot = getWorkspaceResourceRoot(workspace);
            File tomlFile = new File(resourceRoot, "META-INF/neoforge.mods.toml");

            if (!tomlFile.exists()) {
                LOG.info("neoforge.mods.toml not found yet, skipping mixin config injection (will retry on next load)");
                return;
            }

            String content = Files.readString(tomlFile.toPath());

            // Find the custom mixins user code block
            int startIdx = content.indexOf(CUSTOM_MIXINS_START);
            int endIdx = content.indexOf(CUSTOM_MIXINS_END);

            if (startIdx == -1 || endIdx == -1 || endIdx < startIdx) {
                LOG.warn("Could not find custom mixins user code block in neoforge.mods.toml, skipping");
                return;
            }

            // Extract the existing content between the markers
            String existingBlock = content.substring(startIdx + CUSTOM_MIXINS_START.length(), endIdx);

            // Check if our entry is already in the block (or anywhere in the file)
            if (existingBlock.contains("fomek.mixins.json") || content.contains("fomek.mixins.json")) {
                LOG.info("fomek.mixins.json already declared in neoforge.mods.toml");
                return;
            }

            // Our entry is missing — add it AFTER the start marker, preserving
            // all existing content in the block (other [[mixins]] configs, etc.)
            String entry = MIXIN_CONFIG_LINE + "\n" + MIXIN_CONFIG_VALUE + "\n";
            String newContent = content.substring(0, startIdx + CUSTOM_MIXINS_START.length())
                    + "\n" + entry
                    + existingBlock
                    + content.substring(endIdx);

            Files.writeString(tomlFile.toPath(), newContent);
            LOG.info("Injected [[mixins]] config = \"fomek.mixins.json\" into neoforge.mods.toml (preserved existing block content)");

        } catch (Exception e) {
            LOG.error("Failed to inject mixin config into neoforge.mods.toml", e);
        }
    }

    private void injectTemplate(String templateName, String targetDir,
                                 String renderApiPackage, String modPackage, String modId) throws IOException {
        InputStream templateStream = getClass().getClassLoader()
                .getResourceAsStream("templates/" + templateName);
        if (templateStream == null) {
            LOG.warn("Template not found: {}", templateName);
            return;
        }

        String content = new String(templateStream.readAllBytes());
        templateStream.close();

        content = content.replace("__RENDERAPI_PACKAGE__", renderApiPackage);
        content = content.replace("__MOD_PACKAGE__", modPackage);
        content = content.replace("__MODID__", modId);

        File outputFile = new File(targetDir, templateName);
        Files.writeString(outputFile.toPath(), content);

        LOG.debug("Injected: {}", outputFile.getPath());
    }

    private String getModPackage(Workspace workspace) {
        try {
            Object settings = workspace.getWorkspaceSettings();

            try {
                java.lang.reflect.Method m = settings.getClass().getMethod("getModElementsPackage");
                Object result = m.invoke(settings);
                if (result != null && !result.toString().isBlank()) {
                    return result.toString();
                }
            } catch (NoSuchMethodException ignored) {
            }

            for (String methodName : new String[]{
                    "getJavaPackagePath", "getPackageName", "getModPackageName"
            }) {
                try {
                    java.lang.reflect.Method m = settings.getClass().getMethod(methodName);
                    Object result = m.invoke(settings);
                    if (result != null && !result.toString().isBlank()) {
                        return result.toString();
                    }
                } catch (NoSuchMethodException ignored) {
                }
            }

            String sourceRoot = getWorkspaceSourceRoot(workspace);
            File srcDir = new File(sourceRoot);
            if (srcDir.exists()) {
                String found = findPackageFromSource(srcDir);
                if (found != null) return found;
            }

        } catch (Exception e) {
            LOG.error("Failed to get mod package", e);
        }
        return null;
    }

    /**
     * Get the mod ID (modid) from workspace settings.
     * Falls back to the last segment of the mod package if not found.
     */
    private String getModId(Workspace workspace) {
        try {
            Object settings = workspace.getWorkspaceSettings();

            for (String methodName : new String[]{
                    "getModID", "getModId", "getModid"
            }) {
                try {
                    java.lang.reflect.Method m = settings.getClass().getMethod(methodName);
                    Object result = m.invoke(settings);
                    if (result != null && !result.toString().isBlank()) {
                        return result.toString();
                    }
                } catch (NoSuchMethodException ignored) {
                }
            }

        } catch (Exception e) {
            LOG.error("Failed to get mod ID", e);
        }
        return null;
    }

    private String findPackageFromSource(File dir) {
        File[] files = dir.listFiles();
        if (files == null) return null;

        for (File f : files) {
            if (f.isDirectory()) {
                String result = findPackageFromSource(f);
                if (result != null) return result;
            } else if (f.getName().endsWith(".java")) {
                try {
                    for (String line : Files.readAllLines(f.toPath())) {
                        if (line.startsWith("package ")) {
                            return line.replace("package ", "")
                                    .replace(";", "")
                                    .trim();
                        }
                    }
                } catch (IOException ignored) {
                }
            }
        }
        return null;
    }

    private String getWorkspaceSourceRoot(Workspace workspace) {
        File workspaceDir = workspace.getWorkspaceFolder();
        return workspaceDir.getAbsolutePath() + "/src/main/java";
    }

    private String getWorkspaceResourceRoot(Workspace workspace) {
        File workspaceDir = workspace.getWorkspaceFolder();
        return workspaceDir.getAbsolutePath() + "/src/main/resources";
    }
}
